Repository NCATComp410/comp410_spring_2024, pull requests merged in 2024-03, with the labels that each got.

#37 Added test for PERSON
  test_team_guardiansofpii.py
Labels: Guardians-of-PII

#36 Added test for IBAN_CODE
  test_team_futureassured.py
Labels: FutureAssured

#41 added test for au_medicare
  test_team_futureassured.py
Labels: FutureAssured

#35 Added test for us_passport
  test_team_1.py
Labels: Team1

#38 Added test functionality for SG_NRIC_FIN
  test_team_guardiansofpii.py
Labels: Guardians-of-PII

#42 Added test for ip_address
  test_team_1.py
Labels: Team1

#39 5 detect it vat code
  test_team_1.py
Labels: Team1

#45 Added test for it_identity_card
  test_team_3.py
Labels: Team3

#47 Added test for US Bank Numbers
  test_team_3.py
Labels: Team3

#48 Added test for Credit_Card
  test_team_1.py
Labels: Team1

#49 Added test for it_driver_license
  test_team_futureassured.py
Labels: FutureAssured

#40 Added test cases for it_fiscal_code
  test_team_guardiansofpii.py
Labels: Guardians-of-PII

#56 Added tests for date_time
  test_team_3.py
Labels: Team3

#59 Added test for Detect_PHONE_NUMBER
  test_team_futureassured.py
Labels: FutureAssured

#44 Added tests for url
  pii_scan.py
  test_team_2.py
Labels: Team2

#55 Added for It_Passport
  test_team_2.py
Labels: Team2

#57 Added test for location
  test_team_3.py
Labels: Team3

#58 added test for medical_license
  test_team_1.py
Labels: Team1

#62 Updates for sprint3
  case_notes.txt
  pii_scan.py
  test_pii_scan.py
Labels: TeamNull

#60 test for nrp
  test_team_2.py
Labels: Team2
